services:
  - type: web
    name: evpro-monitor
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: MT_MODE
        value: passive
      - key: INGEST_API_KEY
        sync: false
      - key: MT_PAGE_URL
        value: https://gsa.ofalive99.net
      - key: FIREBASE_DATABASE_URL
        value: https://evmtpro-default-rtdb.asia-southeast1.firebasedatabase.app
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
